# Generated by Django 5.2.1 on 2025-09-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('serpapi_result', models.TextField(blank=True, null=True)),
                ('gemini_result', models.TextField(blank=True, null=True)),
                ('factcheck_result', models.TextField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, max_length=255, null=True)),
                ('credibility', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
