# Generated by Django 5.2.1 on 2025-10-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='isFake',
            field=models.BooleanField(default=False),
        ),
    ]
