# Generated by Django 5.2.1 on 2025-10-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ner_app', '0002_queryhistory_isfake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryhistory',
            name='isFake',
        ),
    ]
